### ISSUE TITLE
连接mysql异常 No database found to handle jdbc:mysql

### ISSUE THREAD

**Issue by yanheng** [coolbeevip/flyway-cli#1]
Exception in thread "main" org.flywaydb.core.api.FlywayException: No database found to handle jdbc:mysql://127.0.0.1:3306/mybot
        at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForUrl(DatabaseTypeRegister.java:54)
        at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:109)
        at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:80)
        at org.flywaydb.core.api.configuration.ClassicConfiguration.setDataSource(ClassicConfiguration.java:1061)
        at org.flywaydb.core.api.configuration.FluentConfiguration.dataSource(FluentConfiguration.java:621)
        at org.coolbeevip.flyway.cli.CLI.main(CLI.java:18)

**Comment by yanheng** [comment]
解决 https://github.com/flyway/flyway/issues/3355
